apiVersion: v1
kind: Secret
metadata:
  name: malware-anlaysis-site-secrets
type: Opaque
stringData:
    DJANGO_SECRET: ""
    DB_USER: ""
    DB_PW: ""
    DB_HOST: postgres-service
    EXTRA_HOSTS: ""
    ARCHIVE_PATH: "/RAID"
    ARCHIVE_SITE_TOKEN: ""
    ENABLE_VIRUSTOTAL: "False"
    VTAPI_KEY: "alksf;alkjdf"